// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mapreduceworker.proto

#include "mapreduceworker.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
namespace mapreduce_worker {
}  // namespace mapreduce_worker
static constexpr ::PROTOBUF_NAMESPACE_ID::Metadata* file_level_metadata_mapreduceworker_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_mapreduceworker_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_mapreduceworker_2eproto = nullptr;
const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_mapreduceworker_2eproto::offsets[1] = {};
static constexpr ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema* schemas = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::Message* const* file_default_instances = nullptr;

const char descriptor_table_protodef_mapreduceworker_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\025mapreduceworker.proto\022\020mapreduce_worke"
  "r\032\026mapreduce_common.proto2\247\001\n\017MapReduceW"
  "orker\022F\n\004Work\022\034.mapreduce_common.JobMess"
  "age\032\036.mapreduce_common.EmptyMessage\"\000\022L\n"
  "\010Shutdown\022\036.mapreduce_common.EmptyMessag"
  "e\032\036.mapreduce_common.EmptyMessage\"\000B\024Z\022."
  ";mapreduce_masterb\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_mapreduceworker_2eproto_deps[1] = {
  &::descriptor_table_mapreduce_5fcommon_2eproto,
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_mapreduceworker_2eproto_sccs[1] = {
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_mapreduceworker_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_mapreduceworker_2eproto = {
  false, false, descriptor_table_protodef_mapreduceworker_2eproto, "mapreduceworker.proto", 265,
  &descriptor_table_mapreduceworker_2eproto_once, descriptor_table_mapreduceworker_2eproto_sccs, descriptor_table_mapreduceworker_2eproto_deps, 0, 1,
  schemas, file_default_instances, TableStruct_mapreduceworker_2eproto::offsets,
  file_level_metadata_mapreduceworker_2eproto, 0, file_level_enum_descriptors_mapreduceworker_2eproto, file_level_service_descriptors_mapreduceworker_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_mapreduceworker_2eproto = (static_cast<void>(::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_mapreduceworker_2eproto)), true);
namespace mapreduce_worker {

// @@protoc_insertion_point(namespace_scope)
}  // namespace mapreduce_worker
PROTOBUF_NAMESPACE_OPEN
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
