// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: mapreducemaster.proto

#include "mapreducemaster.pb.h"
#include "mapreducemaster.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace mapreduce_master {

static const char* MapReduceMaster_method_names[] = {
  "/mapreduce_master.MapReduceMaster/ReportStatus",
  "/mapreduce_master.MapReduceMaster/Job",
  "/mapreduce_master.MapReduceMaster/GetStatus",
  "/mapreduce_master.MapReduceMaster/RequestUploadFile",
  "/mapreduce_master.MapReduceMaster/UploadFile",
  "/mapreduce_master.MapReduceMaster/StreamFile",
};

std::unique_ptr< MapReduceMaster::Stub> MapReduceMaster::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< MapReduceMaster::Stub> stub(new MapReduceMaster::Stub(channel));
  return stub;
}

MapReduceMaster::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_ReportStatus_(MapReduceMaster_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Job_(MapReduceMaster_method_names[1], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetStatus_(MapReduceMaster_method_names[2], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_RequestUploadFile_(MapReduceMaster_method_names[3], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_UploadFile_(MapReduceMaster_method_names[4], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_StreamFile_(MapReduceMaster_method_names[5], ::grpc::internal::RpcMethod::CLIENT_STREAMING, channel)
  {}

::grpc::Status MapReduceMaster::Stub::ReportStatus(::grpc::ClientContext* context, const ::mapreduce_master::JobStatus& request, ::mapreduce_common::EmptyMessage* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_ReportStatus_, context, request, response);
}

void MapReduceMaster::Stub::experimental_async::ReportStatus(::grpc::ClientContext* context, const ::mapreduce_master::JobStatus* request, ::mapreduce_common::EmptyMessage* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_ReportStatus_, context, request, response, std::move(f));
}

void MapReduceMaster::Stub::experimental_async::ReportStatus(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::mapreduce_common::EmptyMessage* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_ReportStatus_, context, request, response, std::move(f));
}

void MapReduceMaster::Stub::experimental_async::ReportStatus(::grpc::ClientContext* context, const ::mapreduce_master::JobStatus* request, ::mapreduce_common::EmptyMessage* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_ReportStatus_, context, request, response, reactor);
}

void MapReduceMaster::Stub::experimental_async::ReportStatus(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::mapreduce_common::EmptyMessage* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_ReportStatus_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::mapreduce_common::EmptyMessage>* MapReduceMaster::Stub::AsyncReportStatusRaw(::grpc::ClientContext* context, const ::mapreduce_master::JobStatus& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::mapreduce_common::EmptyMessage>::Create(channel_.get(), cq, rpcmethod_ReportStatus_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::mapreduce_common::EmptyMessage>* MapReduceMaster::Stub::PrepareAsyncReportStatusRaw(::grpc::ClientContext* context, const ::mapreduce_master::JobStatus& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::mapreduce_common::EmptyMessage>::Create(channel_.get(), cq, rpcmethod_ReportStatus_, context, request, false);
}

::grpc::Status MapReduceMaster::Stub::Job(::grpc::ClientContext* context, const ::mapreduce_common::JobMessage& request, ::mapreduce_master::JobStatus* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_Job_, context, request, response);
}

void MapReduceMaster::Stub::experimental_async::Job(::grpc::ClientContext* context, const ::mapreduce_common::JobMessage* request, ::mapreduce_master::JobStatus* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_Job_, context, request, response, std::move(f));
}

void MapReduceMaster::Stub::experimental_async::Job(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::mapreduce_master::JobStatus* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_Job_, context, request, response, std::move(f));
}

void MapReduceMaster::Stub::experimental_async::Job(::grpc::ClientContext* context, const ::mapreduce_common::JobMessage* request, ::mapreduce_master::JobStatus* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_Job_, context, request, response, reactor);
}

void MapReduceMaster::Stub::experimental_async::Job(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::mapreduce_master::JobStatus* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_Job_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::mapreduce_master::JobStatus>* MapReduceMaster::Stub::AsyncJobRaw(::grpc::ClientContext* context, const ::mapreduce_common::JobMessage& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::mapreduce_master::JobStatus>::Create(channel_.get(), cq, rpcmethod_Job_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::mapreduce_master::JobStatus>* MapReduceMaster::Stub::PrepareAsyncJobRaw(::grpc::ClientContext* context, const ::mapreduce_common::JobMessage& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::mapreduce_master::JobStatus>::Create(channel_.get(), cq, rpcmethod_Job_, context, request, false);
}

::grpc::Status MapReduceMaster::Stub::GetStatus(::grpc::ClientContext* context, const ::mapreduce_master::JobStatus& request, ::mapreduce_master::JobStatus* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_GetStatus_, context, request, response);
}

void MapReduceMaster::Stub::experimental_async::GetStatus(::grpc::ClientContext* context, const ::mapreduce_master::JobStatus* request, ::mapreduce_master::JobStatus* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_GetStatus_, context, request, response, std::move(f));
}

void MapReduceMaster::Stub::experimental_async::GetStatus(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::mapreduce_master::JobStatus* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_GetStatus_, context, request, response, std::move(f));
}

void MapReduceMaster::Stub::experimental_async::GetStatus(::grpc::ClientContext* context, const ::mapreduce_master::JobStatus* request, ::mapreduce_master::JobStatus* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_GetStatus_, context, request, response, reactor);
}

void MapReduceMaster::Stub::experimental_async::GetStatus(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::mapreduce_master::JobStatus* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_GetStatus_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::mapreduce_master::JobStatus>* MapReduceMaster::Stub::AsyncGetStatusRaw(::grpc::ClientContext* context, const ::mapreduce_master::JobStatus& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::mapreduce_master::JobStatus>::Create(channel_.get(), cq, rpcmethod_GetStatus_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::mapreduce_master::JobStatus>* MapReduceMaster::Stub::PrepareAsyncGetStatusRaw(::grpc::ClientContext* context, const ::mapreduce_master::JobStatus& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::mapreduce_master::JobStatus>::Create(channel_.get(), cq, rpcmethod_GetStatus_, context, request, false);
}

::grpc::Status MapReduceMaster::Stub::RequestUploadFile(::grpc::ClientContext* context, const ::mapreduce_common::MetaData& request, ::mapreduce_master::JobStatus* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_RequestUploadFile_, context, request, response);
}

void MapReduceMaster::Stub::experimental_async::RequestUploadFile(::grpc::ClientContext* context, const ::mapreduce_common::MetaData* request, ::mapreduce_master::JobStatus* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_RequestUploadFile_, context, request, response, std::move(f));
}

void MapReduceMaster::Stub::experimental_async::RequestUploadFile(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::mapreduce_master::JobStatus* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_RequestUploadFile_, context, request, response, std::move(f));
}

void MapReduceMaster::Stub::experimental_async::RequestUploadFile(::grpc::ClientContext* context, const ::mapreduce_common::MetaData* request, ::mapreduce_master::JobStatus* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_RequestUploadFile_, context, request, response, reactor);
}

void MapReduceMaster::Stub::experimental_async::RequestUploadFile(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::mapreduce_master::JobStatus* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_RequestUploadFile_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::mapreduce_master::JobStatus>* MapReduceMaster::Stub::AsyncRequestUploadFileRaw(::grpc::ClientContext* context, const ::mapreduce_common::MetaData& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::mapreduce_master::JobStatus>::Create(channel_.get(), cq, rpcmethod_RequestUploadFile_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::mapreduce_master::JobStatus>* MapReduceMaster::Stub::PrepareAsyncRequestUploadFileRaw(::grpc::ClientContext* context, const ::mapreduce_common::MetaData& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::mapreduce_master::JobStatus>::Create(channel_.get(), cq, rpcmethod_RequestUploadFile_, context, request, false);
}

::grpc::Status MapReduceMaster::Stub::UploadFile(::grpc::ClientContext* context, const ::mapreduce_common::Chunk& request, ::mapreduce_master::JobStatus* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_UploadFile_, context, request, response);
}

void MapReduceMaster::Stub::experimental_async::UploadFile(::grpc::ClientContext* context, const ::mapreduce_common::Chunk* request, ::mapreduce_master::JobStatus* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_UploadFile_, context, request, response, std::move(f));
}

void MapReduceMaster::Stub::experimental_async::UploadFile(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::mapreduce_master::JobStatus* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_UploadFile_, context, request, response, std::move(f));
}

void MapReduceMaster::Stub::experimental_async::UploadFile(::grpc::ClientContext* context, const ::mapreduce_common::Chunk* request, ::mapreduce_master::JobStatus* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_UploadFile_, context, request, response, reactor);
}

void MapReduceMaster::Stub::experimental_async::UploadFile(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::mapreduce_master::JobStatus* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_UploadFile_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::mapreduce_master::JobStatus>* MapReduceMaster::Stub::AsyncUploadFileRaw(::grpc::ClientContext* context, const ::mapreduce_common::Chunk& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::mapreduce_master::JobStatus>::Create(channel_.get(), cq, rpcmethod_UploadFile_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::mapreduce_master::JobStatus>* MapReduceMaster::Stub::PrepareAsyncUploadFileRaw(::grpc::ClientContext* context, const ::mapreduce_common::Chunk& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::mapreduce_master::JobStatus>::Create(channel_.get(), cq, rpcmethod_UploadFile_, context, request, false);
}

::grpc::ClientWriter< ::mapreduce_common::UploadRequest>* MapReduceMaster::Stub::StreamFileRaw(::grpc::ClientContext* context, ::mapreduce_master::JobStatus* response) {
  return ::grpc_impl::internal::ClientWriterFactory< ::mapreduce_common::UploadRequest>::Create(channel_.get(), rpcmethod_StreamFile_, context, response);
}

void MapReduceMaster::Stub::experimental_async::StreamFile(::grpc::ClientContext* context, ::mapreduce_master::JobStatus* response, ::grpc::experimental::ClientWriteReactor< ::mapreduce_common::UploadRequest>* reactor) {
  ::grpc_impl::internal::ClientCallbackWriterFactory< ::mapreduce_common::UploadRequest>::Create(stub_->channel_.get(), stub_->rpcmethod_StreamFile_, context, response, reactor);
}

::grpc::ClientAsyncWriter< ::mapreduce_common::UploadRequest>* MapReduceMaster::Stub::AsyncStreamFileRaw(::grpc::ClientContext* context, ::mapreduce_master::JobStatus* response, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc_impl::internal::ClientAsyncWriterFactory< ::mapreduce_common::UploadRequest>::Create(channel_.get(), cq, rpcmethod_StreamFile_, context, response, true, tag);
}

::grpc::ClientAsyncWriter< ::mapreduce_common::UploadRequest>* MapReduceMaster::Stub::PrepareAsyncStreamFileRaw(::grpc::ClientContext* context, ::mapreduce_master::JobStatus* response, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncWriterFactory< ::mapreduce_common::UploadRequest>::Create(channel_.get(), cq, rpcmethod_StreamFile_, context, response, false, nullptr);
}

MapReduceMaster::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      MapReduceMaster_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< MapReduceMaster::Service, ::mapreduce_master::JobStatus, ::mapreduce_common::EmptyMessage>(
          std::mem_fn(&MapReduceMaster::Service::ReportStatus), this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      MapReduceMaster_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< MapReduceMaster::Service, ::mapreduce_common::JobMessage, ::mapreduce_master::JobStatus>(
          std::mem_fn(&MapReduceMaster::Service::Job), this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      MapReduceMaster_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< MapReduceMaster::Service, ::mapreduce_master::JobStatus, ::mapreduce_master::JobStatus>(
          std::mem_fn(&MapReduceMaster::Service::GetStatus), this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      MapReduceMaster_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< MapReduceMaster::Service, ::mapreduce_common::MetaData, ::mapreduce_master::JobStatus>(
          std::mem_fn(&MapReduceMaster::Service::RequestUploadFile), this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      MapReduceMaster_method_names[4],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< MapReduceMaster::Service, ::mapreduce_common::Chunk, ::mapreduce_master::JobStatus>(
          std::mem_fn(&MapReduceMaster::Service::UploadFile), this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      MapReduceMaster_method_names[5],
      ::grpc::internal::RpcMethod::CLIENT_STREAMING,
      new ::grpc::internal::ClientStreamingHandler< MapReduceMaster::Service, ::mapreduce_common::UploadRequest, ::mapreduce_master::JobStatus>(
          std::mem_fn(&MapReduceMaster::Service::StreamFile), this)));
}

MapReduceMaster::Service::~Service() {
}

::grpc::Status MapReduceMaster::Service::ReportStatus(::grpc::ServerContext* context, const ::mapreduce_master::JobStatus* request, ::mapreduce_common::EmptyMessage* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status MapReduceMaster::Service::Job(::grpc::ServerContext* context, const ::mapreduce_common::JobMessage* request, ::mapreduce_master::JobStatus* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status MapReduceMaster::Service::GetStatus(::grpc::ServerContext* context, const ::mapreduce_master::JobStatus* request, ::mapreduce_master::JobStatus* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status MapReduceMaster::Service::RequestUploadFile(::grpc::ServerContext* context, const ::mapreduce_common::MetaData* request, ::mapreduce_master::JobStatus* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status MapReduceMaster::Service::UploadFile(::grpc::ServerContext* context, const ::mapreduce_common::Chunk* request, ::mapreduce_master::JobStatus* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status MapReduceMaster::Service::StreamFile(::grpc::ServerContext* context, ::grpc::ServerReader< ::mapreduce_common::UploadRequest>* reader, ::mapreduce_master::JobStatus* response) {
  (void) context;
  (void) reader;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace mapreduce_master

